Repository oz-union-fe-10-team1/ExcellentFE, pull requests merged in 2025-07, with the labels that each got.

#25 style: 공통 컴포넌트(Header) 스타일 수정 (#24)
  src/components/common/Header.tsx
Labels: style

#23 feat: 공통 라벨 컴포넌트 생성(#22)
  src/components/common/Label.tsx
Labels: feat

#28 fix: 버튼 컴포넌트 중복 import 개선(#27)
  src/components/common/Button.tsx
Labels: fix

#32 feat: 공통 컴포넌트 (Modal) 구현 (#15)
  index.html
  package-lock.json
  package.json
  src/assets/icons/modal/close.svg
  src/components/common/Modal.tsx
  src/components/common/Portal.tsx
  src/constants/portalContainerId.ts
Labels: feat

#37 fix: 버튼 컴포넌트 버튼 태그 속성 추가(#36)
  src/components/common/Button.tsx
Labels: fix

#39 feat: svgr 도입 (#38)
  package-lock.json
  package.json
  src/vite-env.d.ts
  vite.config.ts
Labels: feat

#41 feat: 공통 컴포넌트(Icon) 구현 (#40)
  src/components/common/Icon.tsx
Labels: feat

#43 refactor: 기존 아이콘 공통 아이콘 컴포넌트(svgr)로 교체 (#42)
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
Labels: refactor

#45 refactor: 공통 컴포넌트(ItemRow) 공통 아이콘 컴포넌트(svgr)로 교체 (#44)
  src/components/item-row/list-component/CartItemRow.tsx
Labels: refactor

#55 fix: 허스키 권한 수정 (#54)
  .husky/commit-msg
  .husky/pre-commit
Labels: fix

#52 refactor: 공통 컴포넌트(Header) UI 분리 (#51)
  src/App.tsx
  src/components/common/Header.tsx
Labels: refactor

#70 fix: 코드 수정 (#69)
  src/components/common/Input.tsx
Labels: fix

#72 feat: 카드 컴포넌트 디자인 통일 (#61)
  src/components/common/Card.tsx
  src/types/cardProps.ts
Labels: feat

#77 feat: Pretendard 웹폰트 설정 (#75)
  index.html
  src/App.css
Labels: feat
