Repository oz-union-fe-10-team1/ExcellentFE, pull requests merged in 2025-08, with the labels that each got.

#86 fix: 푸터 페이지 별 플로팅 방식 수정 (#85)
  src/components/layout/Footer.tsx
Labels: fix

#133 chore: deploy script 수정 (#132)
  .github/workflows/deploy.yml
Labels: chore

#146 feat: 상세페이지 post api 구현 (#145)
  src/api/productApi.ts
  src/components/detail/DetailProduct.tsx
  src/constants/apiPaths.ts
  src/constants/message.ts
  src/hooks/home/useProduct.ts
  src/hooks/useDetailPage.ts
  src/pages/Detail.tsx
Labels: feat

#165 fix: order api 수정 (#164)
  src/constants/apiPaths.ts
  src/hooks/useOrder.ts
  src/types/orderType.ts
Labels: fix

#179 feat: 검색페이지 api연결 및 후기페이지 상세페이지 연결 (#170)
  src/api/feedbackList/types.ts
  src/api/searchApi.ts
  src/components/common/Pagination.tsx
  src/components/common/cards/BestReviewCard.tsx
  src/components/common/cards/Card.tsx
  src/components/common/cards/ReviewCard.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchResults.tsx
  src/constants/apiPaths.ts
  src/constants/search.ts
  src/hooks/useProductSearch.ts
  src/hooks/useSearchFilters.ts
  src/mocks/handlers.ts
  src/mocks/handlers/product/mocks/productFilterMockData.ts
  src/mocks/handlers/product/mocks/productSearchMockData.ts
  src/mocks/handlers/product/product.ts
  src/pages/Feedback.tsx
  src/pages/Search.tsx
  src/types/cardProps.ts
  src/types/search.ts
  src/utils/searchParams.ts
Labels: feat, fix, style

#197 design: 계정 찾기 UI 제거 (#196)
  src/pages/auth/Login.tsx
Labels: design

#204 feat: 소셜(카카오톡, 페이스북) 으로 공유하기 기능, url 공유하기 기능 구현
  index.html
  src/assets/icons/tasteTest/urlShare.svg
  src/components/test/KakaoShareButton.tsx
  src/components/test/MainStep.tsx
  src/components/test/ResultStep.tsx
  src/types/kakao.d.ts
Labels: feat

#206 chore: deploy.yml 수정 (#205)
  .github/workflows/deploy.yml
Labels: chore

#212 chore: deploy.yml 수정 (#211)
  .github/workflows/deploy.yml
  README.md
Labels: docs, chore

#218 hotfix: 성인인증 통과 후 성인인증메뉴얼페이지로 리다이렉트되는 문제 해결 (#216)
  src/hooks/auth/useAdultAuth.ts
  src/pages/auth/AdultCallback.tsx
Labels: release
